import React from "react";
import SampleContainer from "./SampleContainer";

function BookSample() {
  return (
    <section className="book-samples mt-32 mb-20 text-center mx-20">
      <h2 className="mb-5 text-2xl font-medium text-textColor text-center">
        Sample Books Generated by BookAI
      </h2>
      <p>
        Explore some of the captivating books created using our AI technology.
      </p>
      <SampleContainer/>
    </section>
  );
}

export default BookSample;
